<?php
/**
 * @file
 * Provides administrative tools for managing Ubercart file downloads and their
 * users.
 */

/**
 * Implements hook_menu().
 */
function uc_file_users_menu() {

  $items['admin/store/products/file-users'] = array(
    'title' => 'View file download users',
    'description' => 'Show users for file downloads.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('uc_file_users_form'),
    'access arguments' => array('administer products'),
    'file' => 'uc_file_users.admin.inc',
  );
  $items['admin/store/products/file-users/%'] = array(
    'title' => 'View file download users',
    'description' => 'Show users for a specified download file.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('uc_file_users_file_form', 4),
    'access arguments' => array('administer products'),
    'file' => 'uc_file_users.admin.inc',
    'type' => MENU_CALLBACK,
  );

  // Autocomplete helpers

  $items['_uc_file_users_autocomplete'] = array(
    'page callback' => '_uc_file_users_autocomplete',
    'access arguments' => array('administer products'),
    'file' => 'uc_file_users.admin.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}
